# Generated by Django 2.2.5 on 2019-09-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryDataCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=1000, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('truth', models.CharField(max_length=100, null=True)),
                ('cube', models.CharField(max_length=100, null=True)),
                ('google', models.CharField(max_length=100, null=True)),
                ('google_spam', models.CharField(max_length=100, null=True)),
                ('google_not_spam', models.CharField(max_length=100, null=True)),
                ('ibm', models.CharField(max_length=100, null=True)),
                ('ibm_spam', models.CharField(max_length=100, null=True)),
                ('ibm_not_spam', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
